# Generated by Django 5.0.3 on 2024-05-10 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carreto', '0001_initial'),
        ('pagaments', '0002_pagament_unique_user_pagament'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField(auto_now_add=True)),
                ('carreto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carreto.carrito')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagaments.user')),
            ],
        ),
    ]
