# Generated by Django 5.0.4 on 2024-05-08 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pagament',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tarjet_num', models.CharField(max_length=100)),
                ('exp_date', models.DateField()),
                ('cvc', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagaments.user')),
            ],
        ),
    ]
