# Generated by Django 5.0.3 on 2024-04-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagaments', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pagament',
            constraint=models.UniqueConstraint(fields=('user_id',), name='unique_user_pagament'),
        ),
    ]
