# Generated by Django 5.0.4 on 2024-04-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cataleg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('productos', models.ManyToManyField(to='cataleg.producte')),
            ],
        ),
    ]
